version: "3.8"

services:
  nginx:
    image: nginx:1.21.3
    container_name: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./static:/static
    depends_on:
      - django

  mysql:
    image: mysql:5.7
    container_name: mysql
    # platform: linux/x86_64
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "4306:3306"
    env_file:
      - ./mysql/.env
    volumes:
      - ./mysql/DataBase:/var/lib/mysql
      - ./mysql/sql:/docker-entrypoint-initdb.d

  django:
    build: ./django
    container_name: django
    command: uwsgi --socket :8001 --module raretechlove.wsgi --py-autoreload 1 --logto /tmp/mylog.log
    volumes:
      - ./django:/code
      - ./static:/static
    expose:
      - "8001"
    env_file:
      - ./django/.env
    depends_on:
      - mysql
