# Generated by Django 3.2.7 on 2021-09-12 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raretechloveapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermst',
            name='spread_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
