# Generated by Django 3.2.7 on 2021-09-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raretechloveapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemst',
            name='level',
            field=models.CharField(choices=[('初級', '初級'), ('中級', '中級'), ('上級', '上級')], default=1, max_length=255, verbose_name='難易度'),
            preserve_default=False,
        ),
    ]
