FROM python:3.9.7
RUN mkdir /code
WORKDIR /code
ADD requirements.txt /code/
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install requests
RUN pip install django-crontab
ADD . /code/
