GRANT ALL PRIVILEGES ON db.* TO 'user'@'%';

FLUSH PRIVILEGES;

DROP DATABASE IF EXISTS RareTECHLoveDB;
CREATE DATABASE RareTECHLoveDB;
USE RareTECHLoveDB;

DROP TABLE IF EXISTS USER_MST;
CREATE TABLE USER_MST
(
  user_cd INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_name VARCHAR(255) NOT NULL,
  pw VARCHAR(255) NOT NULL,
  slack_name VARCHAR(255) NOT NULL,
);

DROP TABLE IF EXISTS ARTICLE_MST;
CREATE TABLE ARTICLE_MST
(
  artile_cd INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  artile_url VARCHAR(255) NOT NULL,
  category VARCHAR(255) NOT NULL,
  artile_rank VARCHAR(255) NOT NULL,
  article_title VARCHAR(21844) NOT NULL
);

DROP TABLE IF EXISTS Q_COUNT_TBL;
CREATE TABLE Q_COUNT_TBL
(
  q_cd INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  q_cnt INT NULL,
  a_cnt INT NULL,
);

DROP TABLE IF EXISTS QUESTION_TBL;
CREATE TABLE QUESTION_TBL
(
  ts_cd INT NOT NULL AUTO_INCREMENT,
  artile_cd INT NOT NULL,
  user_cd INT NOT NULL,
  quetion_thred VARCHAR(21844) NOT NULL,
  ts timestamp NOT NULL,
  qa_dist BOOLEAN NOT NULL,
);








