# BUILDER #
 
FROM python:3.9.7-alpine3.14

WORKDIR /usr/src/app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# create Django directory for the app user
ENV APP_HOME=/usr/src/app
RUN mkdir -p $APP_HOME && \
    mkdir $APP_HOME/staticfiles && \
    mkdir $APP_HOME/mediafiles

# create the app user
RUN addgroup -S app && adduser -S app -G app

# set work directory
WORKDIR $APP_HOME

# install dependencies
# COPY ./Pipfile .
# COPY ./Pipfile.lock .
# RUN apk update && \
#     apk add postgresql-dev gcc python3-dev musl-dev libpq && \
#     pip install --upgrade pip && \
#     pip install pipenv && \
#     pipenv install --dev --system

# COPY ./django_project/raretechloveapp/templates /var/www/html

RUN apt-get update && \
    apt-get -y install gcc \
    libmariadb-dev \
    git \
    zip \
    unzip \
    vim \
    libpng-dev \
    libpq-dev

RUN pip install --upgrade pip
RUN pip install flake8
COPY . .
 
# COPY ./requirements.txt .
# RUN pip -r requirements.txt


# copy entrypoint shell file
COPY ./entrypoint.development.sh $APP_HOME

# copy project
COPY . $APP_HOME

# chown all the files to the app user
RUN chown -R app:app $APP_HOME

# change to the app user
USER app

# run entrypoint shell file
ENTRYPOINT ["/usr/src/app/entrypoint.development.sh"]